"""Core contracts shared by ingestion, query, response, and adapters."""

from src.core.types import (
    Chunk,
    ChunkRecord,
    Citation,
    CollectionInfo,
    DeleteResult,
    Document,
    DocumentSummary,
    EvaluationCase,
    EvaluationReport,
    ImagePayload,
    ImageRef,
    IngestionRequest,
    IngestionResult,
    JsonDict,
    Metadata,
    ProcessedQuery,
    ProgressCallback,
    QueryRequest,
    QueryResponse,
    RetrievalCandidate,
    SearchHit,
    SparseVector,
    Vector,
)

__all__ = [
    "Chunk",
    "ChunkRecord",
    "Citation",
    "CollectionInfo",
    "DeleteResult",
    "Document",
    "DocumentSummary",
    "EvaluationCase",
    "EvaluationReport",
    "ImagePayload",
    "ImageRef",
    "IngestionRequest",
    "IngestionResult",
    "JsonDict",
    "Metadata",
    "ProcessedQuery",
    "ProgressCallback",
    "QueryRequest",
    "QueryResponse",
    "RetrievalCandidate",
    "SearchHit",
    "SparseVector",
    "Vector",
]
